feat: web socket support
soracom/beamtest pull request #11
Opened 2024-04-30 00:50 UTC by kouseii

2024-05-07 07:26 UTC, pachirel requested changes
@kouseii ありがとうございます！2点あります。

1.  rspec-eventmachine を追加しないようにはできないでしょうか。native extension も入るようですし、10年前から更新がないので追加したくない気持ちがあります。
2. なぜか追加されたテストが通らないみたいです。環境依存かもしれません。

```shell
% bundle exec rspec spec
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}
.....................FFFFF.

Failures:

  1) WebSocket should receive a greeting message
     Failure/Error: expect(@message).to eq(message)
     
       expected: "Hello SORACOM Beam Client !"
            got: nil
     
       (compared using ==)
     # ./spec/app_spec.rb:370:in `check_message'
     # ./spec/app_spec.rb:359:in `block in wait_for_message'

  2) WebSocket should receive a echo back
     Failure/Error: expect(@message).to eq(message)
     
       expected: "Hello"
            got: nil
     
       (compared using ==)
     # ./spec/app_spec.rb:370:in `check_message'
     # ./spec/app_spec.rb:359:in `block in wait_for_message'

  3) WebSocket should receive a greeting message with UE ids
     Failure/Error: expect(@message).to eq(message)
     
       expected: "Hello SORACOM Beam Client IMSI:440101234567890 SIM ID:8981100024620429680 MSISDN:8180123456780000 IMEI:123456789012345 !"
            got: nil
     
       (compared using ==)
     # ./spec/app_spec.rb:370:in `check_message'
     # ./spec/app_spec.rb:359:in `block in wait_for_message'

  4) WebSocket when signature is provided should receive a greeting message with UE ids
     Failure/Error: expect(@message).to eq(message)
     
       expected: "Hello SORACOM Beam Client IMSI:440101234567890 SIM ID:8981100024620429680 MSISDN:8180123456780000 IMEI:123456789012345 !"
            got: nil
     
       (compared using ==)
     # ./spec/app_spec.rb:370:in `check_message'
     # ./spec/app_spec.rb:359:in `block in wait_for_message'

  5) WebSocket when invalid signature is provided should receive 403
     Failure/Error: expect(@error_event.current_target.status).to eq(status)
     
       expected: 403
            got: nil
     
       (compared using ==)
     # ./spec/app_spec.rb:375:in `check_status'
     # ./spec/app_spec.rb:318:in `block in open_socket'
     # ./spec/app_spec.rb:331:in `block in open_socket'

Finished in 31.24 seconds (files took 14.31 seconds to load)
27 examples, 5 failures

Failed examples:

rspec ./spec/app_spec.rb:403 # WebSocket should receive a greeting message
rspec ./spec/app_spec.rb:412 # WebSocket should receive a echo back
rspec ./spec/app_spec.rb:425 # WebSocket should receive a greeting message with UE ids
rspec ./spec/app_spec.rb:440 # WebSocket when signature is provided should receive a greeting message with UE ids
rspec ./spec/app_spec.rb:459 # WebSocket when invalid signature is provided should receive 403
```

2024-05-07 07:26 UTC, pachirel commented on http/app.rb
> +$stdout.sync = true
参考までに使っている lint tool を教えていただけないでしょうか。

2024-05-07 07:26 UTC, pachirel commented on http/app.rb
> +def signature?(env)
```suggestion
# リクエストヘッダーにユーザーによる署名が含まれているかどうかを判定します。署名の検証は行いません。
def signature?(env)
```

2024-05-07 07:26 UTC, pachirel commented on http/app.rb
> +def signature?(env)
`HTTP_X_SORACOM_IMSI` などのヘッダー名に typo があったときに署名がないものとして扱われてしまうので、もともとのロジック（単に `HTTP_X_SORACOM_SIGNATURE` の有無を見る）ほうが自然かなと思いました。

2024-05-07 07:26 UTC, pachirel commented on http/Gemfile
> +  gem 'rspec-eventmachine', '~> 0.2.0'
@kouseii この gem がとても古いので、できれば依存したくないのですが、可能でしょうか？

2024-05-07 08:14 UTC, kouseii commented on http/app.rb
> +$stdout.sync = true
RuboCop かな。
VSCode に Shopify.ruby-lsp plugin を install したら指摘されるようになりました。

2024-05-07 14:10 UTC, kouseii commented on http/app.rb
> +def signature?(env)
了解です。
HTTP_X_SORACOM_SIGNATURE だけ確認しますね。

2024-05-07 14:10 UTC, kouseii commented on http/Gemfile
> +  gem 'rspec-eventmachine', '~> 0.2.0'
rspec-eventmachine を使わずに EventMachine を直接使う方法が分かったので、対応してみます。

2024-05-07 14:12 UTC, kouseii commented
@pachirel 
以下で対応しましたー。
[5a0a1ec](https://github.com/soracom/beamtest/pull/11/commits/5a0a1ec3fee137103ca095a545ccc86882a63204)
[e9842a8](https://github.com/soracom/beamtest/pull/11/commits/e9842a8142260c99ca21e86f7c46f9b0db0a2c76)

これで test が動かなかったら、疑うは Ruby のバージョンかなー。
流石に EventMachine が環境依存で動かない事は無いと信じたいです。

2024-05-08 02:17 UTC, pachirel approved these changes
LGTM!

2024-05-08 04:43 UTC, tokidoki11 commented
notice: Works on my m3 pro mac

<img width="586" alt="image" src="https://github.com/soracom/beamtest/assets/7564844/ef2d4d41-beb6-4679-ba4c-0e6da5c08c0e">

2024-05-08 06:04 UTC, kouseii commented
ご確認ありがとうございますしたー。
デプロイ作業も計画しますね。

2024-05-08 06:04 UTC, merged